export const ADD_BUG_REQUEST = 'ADD_BUG_REQUEST'
export const ADD_BUG_SUCCESS = 'ADD_BUG_SUCCESS'
export const ADD_BUG_FAIL = 'ADD_BUG_FAIL'
export const ADD_BUG_RESTORE = 'ADD_BUG_RESTORE'


export const GET_BUGS_REQUEST = 'GET_BUGS_REQUEST'
export const GET_BUGS_SUCCESS = 'GET_BUGS_SUCCESS'
export const GET_BUGS_FAIL = 'GET_BUGS_FAIL'


export const GET_BUG_BY_ID_REQUEST = 'GET_BUG_BY_ID_REQUEST'
export const GET_BUG_BY_ID_SUCCESS = 'GET_BUG_BY_ID_SUCCESS'
export const GET_BUG_BY_ID_FAIL = 'GET_BUG_BY_ID_FAIL'


export const REMOVE_BUG_REQUEST = 'REMOVE_BUG_REQUEST'
export const REMOVE_BUG_SUCCESS = 'REMOVE_BUG_SUCCESS'
export const REMOVE_BUG_FAIL = 'REMOVE_BUG_FAIL'
export const REMOVE_BUG_RESTORE = 'REMOVE_BUG_RESTORE'


export const CHANGE_BUG_STATUS_REQUEST = 'CHANGE_BUG_STATUS_REQUEST'
export const CHANGE_BUG_STATUS_SUCCESS = 'CHANGE_BUG_STATUS_SUCCESS'
export const CHANGE_BUG_STATUS_FAIL = 'CHANGE_BUG_STATUS_FAIL'
export const CHANGE_BUG_STATUS_RESTORE = 'CHANGE_BUG_STATUS_CHANGE_BUG_STATUS_RESTORE'


export const EDIT_BUG_REQUEST = 'EDIT_BUG_REQUEST'
export const EDIT_BUG_SUCCESS = 'EDIT_BUG_SUCCESS'
export const EDIT_BUG_FAIL = 'EDIT_BUG_FAIL'
export const EDIT_BUG_RESTORE = 'EDIT_BUG_RESTORE'


export const MODAL_OPEN_ADD = 'MODAL_OPEN_ADD'
export const MODAL_OPEN_EDIT = 'MODAL_OPEN_EDIT'
export const MODAL_CLOSE = 'MODAL_CLOSE'


export const CHANGE_PAGE = 'CHANGE_PAGE'
export const CHANGE_PAGES = 'CHANGE_PAGES'
export const SEARCH = 'SEARCH'
export const SORT = 'SORT'


